@startuml

interface FileParser {
    async parse(file: string) : void
}

interface HtmlParser {
    async parse(element: Element) : void
}
interface AnchorParser {
    canParse(anchor: HTMLAnchorElement) : bool
    async parse(file: string, anchor: HTMLAnchorElement) : string;
}

CompositeFileParser *-- "has many" FileParser
CompositeFileParser ..|> FileParser
FileParser <|.. AsyncapiFileParser
FileParser <|.. DashboardFileParser
FileParser <|.. DrawIOFileParser
FileParser <|.. FeatureFileParser
FileParser <|.. MarkdownFileParser
FileParser <|.. MarkdownMessageFileParser
FileParser <|.. OpenapiFileParser
FileParser <|.. UmlFileParser
FileParser <|.. UserTaskFileParser

MarkdownFileParser --> "uses" MarkdownRenderer

MarkdownRenderer *-- "has many" HtmlParser

HtmlParser <|.. AnchorHtmlParser
HtmlParser <|.. CleanUpHtmlParser
HtmlParser <|.. DefinitionHtmlParser
HtmlParser <|.. FullscreenHtmlParser
HtmlParser <|.. HeadingHtmlParser
HtmlParser <|.. ImageHtmlParser
HtmlParser <|.. UnsortedListHtmlParser

AnchorHtmlParser *-- "has many" AnchorParser
AnchorParser <|.. BPMNAnchorParser
AnchorParser <|.. CodeAnchorParser
AnchorParser <|.. IFrameAnchorParser
AnchorParser <|.. UrlRewriteAnchorParser

@enduml