name: md-docs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [test-execution-changed]

jobs:

  md-docs:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download
        uses: synionnl/md-docs-actions/azure/download@main
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: test-excecutions
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}

      - name: Build
        uses: synionnl/md-docs-actions/build@main

      - name: Deploy
        uses: synionnl/md-docs-actions/github/deploy@main
        with:
          destination_directory: products